kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: uiservice
spec:
  ports:
    - port: 80                               # Containers port exposed
      targetPort: 80                     # Pods port
  selector:
    run: my-ui                    
  type: NodeIP

