kind: Pod
apiVersion: v1
metadata:
  name: ui-pod
  labels:
    myvalue: ui-pod                                # Label for applying service later
spec:
  containers:
    - name: ui01
      image: chetangsanghi/kube-ui-httpd:0.1
      ports:
       - containerPort: 80                         # Expose port 80 from container

